const PokemonList = [
  {
    name: "Bulbasaur",
    id: "001",
    image: "/bulbasaur.svg",
    color: "#74CB48",
    secondary_color: "#A43E9E",
    main_type: "Grass",
    secondary_type: "Poison",
    weight: "6,9kg",
    height: "0,7m",
    main_ability: "Chlorophyll",
    secondary_ability: "Overgrow",
    description:
      "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    stats: {
      hp: "045",
      atk: "049",
      def: "049",
      satk: "065",
      sdef: "065",
      spd: "045",
    },
  },
  {
    name: "Charmander",
    id: "004",
    image: "/charmander.svg",
    color: "#f57d31",
    secondary_color: "",
    main_type: "Fire",
    secondary_type: "",
    weight: "8,5kg",
    height: "0,6m",
    main_ability: "Mega-Punch",
    secondary_ability: "Fire-Punch",
    description:
      "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    stats: {
      hp: "039",
      atk: "052",
      def: "043",
      satk: "060",
      sdef: "050",
      spd: "065",
    },
  },
  {
    name: "Squirtle",
    id: "007",
    image: "/squirtle.svg",
    color: "#6493EB",
    secondary_color: "",
    main_type: "Water",
    secondary_type: "",
    weight: "9,0kg",
    height: "0,5m",
    main_ability: "Tarrent",
    secondary_ability: "Rain-Dish",
    description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
      hp: "044",
      atk: "048",
      def: "065",
      satk: "050",
      sdef: "064",
      spd: "043",
    },
  },
  {
    name: "Butterfree",
    id: "012",
    image: "/butterfree.svg",
    color: "#A7B723",
    secondary_color: "#A891EC",
    main_type: "Bug",
    secondary_type: "Flying",
    weight: "32,0kg",
    height: "1,1m",
    main_ability: "Compound-Eyes",
    secondary_ability: "Tinted-Lens",
    description:
      "In battle, it florps its wings at great speed to release highly toxic dust into the air.",
    stats: {
      hp: "060",
      atk: "045",
      def: "050",
      satk: "090",
      sdef: "080",
      spd: "070",
    },
  },
  {
    name: "Pikachu",
    id: "025",
    image: "/pikachu.svg",
    color: "#F9CF30",
    secondary_color: "",
    main_type: "Electric",
    secondary_type: "",
    weight: "6,0kg",
    height: "0,4m",
    main_ability: "Mega-Punch",
    secondary_ability: "Pay-Day",
    description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra sorft and super strechy.",
    stats: {
      hp: "035",
      atk: "055",
      def: "040",
      satk: "050",
      sdef: "050",
      spd: "090",
    },
  },
  {
    name: "Gastly",
    id: "092",
    image: "/gastly.svg",
    color: " #70559B",
    secondary_color: "#A43E9E",
    main_type: "Ghost",
    secondary_type: "Poison",
    weight: "0,1kg",
    height: "1,3m",
    main_ability: "Levitate",
    secondary_ability: "",
    description:
      "Born from gases, anyone would faint if enguifed by its gaseous body, wich contains poison.",
    stats: {
      hp: "030",
      atk: "035",
      def: "030",
      satk: "100",
      sdef: "035",
      spd: "080",
    },
  },
  {
    name: "Ditto",
    id: "132",
    image: "/ditto.svg",
    color: "#AAA67F",
    secondary_color: "",
    main_type: "Normal",
    secondary_type: "",
    weight: "4,0kg",
    height: "0,3m",
    main_ability: "Limber imposter",
    secondary_ability: "",
    description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    stats: {
      hp: "048",
      atk: "048",
      def: "048",
      satk: "048",
      sdef: "048",
      spd: "048",
    },
  },
  {
    name: "Mew",
    id: "152",
    image: "/mew.svg",
    color: "#FB5584",
    secondary_color: "",
    main_type: "Psychic",
    secondary_type: "",
    weight: "4,0kg",
    height: "0,4m",
    main_ability: "Synchronize",
    secondary_ability: "",
    description:
      "When viewed through a microscop, this Pokemon's short,fine,delicate hair can be seen.",
    stats: {
      hp: "100",
      atk: "100",
      def: "100",
      satk: "100",
      sdef: "100",
      spd: "100",
    },
  },
  {
    name: "Aron",
    id: "304",
    image: "/aron.svg",
    color: "#B7B9D0",
    secondary_color: "#B69E31",
    main_type: "Steel",
    secondary_type: "Rock",
    weight: "60,0kg",
    height: "0,4m",
    main_ability: "Sturdy",
    secondary_ability: "Rock-Head",
    description:
      "It eats iron are - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    stats: {
      hp: "050",
      atk: "070",
      def: "100",
      satk: "040",
      sdef: "040",
      spd: "030",
    },
  },
];

export default PokemonList;
