const PokemonList = [
  {
    name: "Bulbasaur",
    id: "001",
    image: "/bulbasaur.svg",
    color: "#74CB48",
    secondary_color: "#A43E9E",
    main_type: "Grass",
    secondary_type: "Poison",
    weight: "6,9kg",
    height: "0,7m",
    main_ability: "Chlorophyll",
    secondary_ability: "Overgrow",
    description:
      "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    stats: {
      hp: 45,
      atk: 49,
      def: 49,
      satk: 65,
      sdef: 65,
      spd: 45,
    },
  },
  {
    name: "Charmander",
    id: "004",
    image: "/charmander.svg",
    color: "#f57d31",
    secondary_color: "",
    main_type: "Fire",
    secondary_type: "",
    weight: "8,5kg",
    height: "0,6m",
    main_ability: "Mega-Punch",
    secondary_ability: "Fire-Punch",
    description:
      "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    stats: {
      hp: 39,
      atk: 52,
      def: 43,
      satk: 60,
      sdef: 50,
      spd: 65,
    },
  },
  {
    name: "Squirtle",
    id: "007",
    image: "/squirtle.svg",
    color: "#6493EB",
    secondary_color: "",
    main_type: "Water",
    secondary_type: "",
    weight: "9,0kg",
    height: "0,5m",
    main_ability: "Tarrent",
    secondary_ability: "Rain-Dish",
    description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
      hp: 44,
      atk: 48,
      def: 65,
      satk: 50,
      sdef: 64,
      spd: 43,
    },
  },
  {
    name: "Butterfree",
    id: "012",
    image: "/butterfree.svg",
    color: "#A7B723",
    secondary_color: "#A891EC",
    main_type: "Bug",
    secondary_type: "Flying",
    weight: "32,0kg",
    height: "1,1m",
    main_ability: "Compound-Eyes",
    secondary_ability: "Tinted-Lens",
    description:
      "In battle, it florps its wings at great speed to release highly toxic dust into the air.",
    stats: {
      hp: 60,
      atk: 45,
      def: 50,
      satk: 90,
      sdef: 80,
      spd: 70,
    },
  },
  {
    name: "Pikachu",
    id: "025",
    image: "/pikachu.svg",
    color: "#F9CF30",
    secondary_color: "",
    main_type: "Electric",
    secondary_type: "",
    weight: "6,0kg",
    height: "0,4m",
    main_ability: "Mega-Punch",
    secondary_ability: "Pay-Day",
    description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra sorft and super strechy.",
    stats: {
      hp: 35,
      atk: 55,
      def: 40,
      satk: 50,
      sdef: 50,
      spd: 90,
    },
  },
  {
    name: "Gastly",
    id: "092",
    image: "/gastly.svg",
    color: " #70559B",
    secondary_color: "#A43E9E",
    main_type: "Ghost",
    secondary_type: "Poison",
    weight: "0,1kg",
    height: "1,3m",
    main_ability: "Levitate",
    secondary_ability: "",
    description:
      "Born from gases, anyone would faint if enguifed by its gaseous body, wich contains poison.",
    stats: {
      hp: "030",
      atk: "035",
      def: 30,
      satk: 100,
      sdef: 35,
      spd: 80,
    },
  },
  {
    name: "Ditto",
    id: "132",
    image: "/ditto.svg",
    color: "#AAA67F",
    secondary_color: "",
    main_type: "Normal",
    secondary_type: "",
    weight: "4,0kg",
    height: "0,3m",
    main_ability: "Limber imposter",
    secondary_ability: "",
    description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    stats: {
      hp: 48,
      atk: 48,
      def: 48,
      satk: 48,
      sdef: 48,
      spd: 48,
    },
  },
  {
    name: "Mew",
    id: "152",
    image: "/mew.svg",
    color: "#FB5584",
    secondary_color: "",
    main_type: "Psychic",
    secondary_type: "",
    weight: "4,0kg",
    height: "0,4m",
    main_ability: "Synchronize",
    secondary_ability: "",
    description:
      "When viewed through a microscop, this Pokemon's short,fine,delicate hair can be seen.",
    stats: {
      hp: 100,
      atk: 100,
      def: 100,
      satk: 100,
      sdef: 100,
      spd: 100,
    },
  },
  {
    name: "Aron",
    id: "304",
    image: "/aron.svg",
    color: "#B7B9D0",
    secondary_color: "#B69E31",
    main_type: "Steel",
    secondary_type: "Rock",
    weight: "60,0kg",
    height: "0,4m",
    main_ability: "Sturdy",
    secondary_ability: "Rock-Head",
    description:
      "It eats iron are - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    stats: {
      hp: 50,
      atk: 70,
      def: 100,
      satk: 40,
      sdef: 40,
      spd: 30,
    },
  },
];

export default PokemonList;
